[general]
blog_author = "Bob"
blog_copyright_year = 2023
blog_email = "bob@example.com"
features = ["tags", "postlisting"]

[feature-navbar]
order = ["index", "projects", "about"]

[feature-postlisting]
order = "ascending"
 
[feature-tags]
sort_by = "count" # Order by name

