[general]
blog_author = "Bob"
blog_copyright_year = 2023
blog_email = "bob@example.com"
features = ["navbar", "postlisting"]

[feature-navbar]
links = ["home.md", "posts.md", "about.md"]

[feature-postlisting]
tags_enabled = true
post_listing_page = "posts.md"
post_listing_order = "newestontop"
tag_listing_order = "count"
tag_listing_page = "tags.md"

