[general]
blog_author = "Bob"
blog_copyright_year = 2023
blog_email = "bob@example.com"
features = ["navbar", "postlisting"]

[feature-navbar]
links = ["home.md", "posts.md", "about.md"]

[feature-postlisting]
order = "newestontop"
 
[feature-tags]
sort_by = "count" # Order by name

